version: '3.8'

services:
 api:
  build:
    context: ./
  ports:
  - 8000:8000
  env_file:
  - .env
  depends_on:
    - psqldbgame

 psqldbgame:
  image: postgres
  container_name: "psqldbgame"
  restart: always
  ports:
  - 3306:5432
  env_file:
  - .env
